### ISSUE TITLE
大佬，replit的服务如何进程守护呢

### ISSUE THREAD

**Issue by nickboyabc** [jeckun/ChatGPT-bot-in-python#1]
请教大佬，在replit挂的服务，启动后如果关闭了网页服务就断了
后来加了nohup命令发现也不行

**Comment by jeckun** [comment]
我不是大佬，我也是刚开始用replit，我也遇到这种情况。估计是因为在用免费使用，所以replit不会给太多资源。如果购买了他们的服务，估计就不会这样了。

**Comment by nickboyabc** [comment]
> 我不是大佬，我也是刚开始用replit，我也遇到这种情况。估计是因为在用免费使用，所以replit不会给太多资源。如果购买了他们的服务，估计就不会这样了。

感谢回复，老铁是replit的付费用户么，国外的产品支付很不方便，刚才瞧了下replit120刀一年也不便宜了性价比不高，国内可以上大厂2核4G的轻量应用服务器了

**Comment by jeckun** [comment]
我也没付费，就是试用一下。如果想正式部署，还是需要找到合适的服务器。
